Repository OneCareerJP/mina-ui, pull requests merged in 2021-07, with the labels that each got.

#30 Added new iconName
  src/components/atoms/MIcon/MIcon.stories.js
  src/components/atoms/MIcon/MIcon.vue
Labels: enhancement, ✅ Approved

#31 fix MModal Component
  src/components/atoms/MModal/MModal.vue
Labels: bug, ✅ Approved

#29 fix:MAlert.vue
  src/components/molecules/MAlert/MAlert.vue
Labels: ✅ Approved

#32 feat: add error color
  src/components/atoms/MInputText/MInputText.vue
  src/components/atoms/MInputText/types.ts
  src/components/atoms/MTypography/MBody/MBody.stories.js
  src/components/atoms/MTypography/MBody/MBody.vue
Labels: ✅ Approved

#33 build
  dist/mina-ui.common.js
  dist/mina-ui.common.js.map
  dist/mina-ui.css
  dist/mina-ui.umd.js
  dist/mina-ui.umd.js.map
  dist/mina-ui.umd.min.js
  dist/mina-ui.umd.min.js.map
Labels: ✅ Approved

#34 add bold to props
  src/components/atoms/MButton/MButton.vue
  src/components/atoms/MButton/types.ts
Labels: enhancement, ✅ Approved

#35 v0.1.3
  package.json
Labels: ✅ Approved

#36 build
  dist/mina-ui.common.js
  dist/mina-ui.common.js.map
  dist/mina-ui.css
  dist/mina-ui.umd.js
  dist/mina-ui.umd.js.map
  dist/mina-ui.umd.min.js
  dist/mina-ui.umd.min.js.map
  src/components/molecules/MAlert/MAlert.stories.js
  src/components/molecules/MAlert/MAlert.vue
Labels: ✅ Approved

#38 fix/MINA-488: 企業ページの切り抜きが適切でない
  dist/mina-ui.common.js
  dist/mina-ui.common.js.map
  dist/mina-ui.css
  dist/mina-ui.umd.js
  dist/mina-ui.umd.js.map
  dist/mina-ui.umd.min.js
  dist/mina-ui.umd.min.js.map
  src/components/atoms/MInputFile/MInputFile.vue
Labels: bug, ✅ Approved

#39 update node
  .node-version
Labels: ✅ Approved, 🔍 Ready for Review

#37 add: npm publish workflow
  .github/workflows/release.yml
Labels: 🔍 Ready for Review

#40 v0.1.4
  package.json
Labels: 🔍 Ready for Review
